spring:
  batch:
    job:
      enabled: false

batch:
  virtualAccountCardConnect:
    config:
      chunkSize: 1000
    file:
      localPath: /home/vam/batch/raw_data/
      nasPath: /home/vam/batch/raw_data/
      rawPrefix: raw_data_additional_
      rawSuffix: .SAM
      encPrefix: enc_