-- `VAM_CHRG_TR_HIST` Table 백업
ALTER TABLE VAM.VAM_VT_ACN_LIST RENAME TO VAM_VT_ACN_LIST_BACKUP;

-- `VAM_VT_ACN_LIST` Table 생성
CREATE TABLE VAM.VAM_VT_ACN_LIST
(
    VT_ACN_LIST_SNO          NUMBER(22) PRIMARY KEY,
    ENC_VT_ACNO              VARCHAR(44)  NOT NULL,
    BANK_CD                  VARCHAR(3)   NOT NULL,
    VT_ACN_ST_DV_CD          VARCHAR(8)   NOT NULL,
    VT_ACN_CONN_DV_CD        VARCHAR(8)   NOT NULL,
    PAR_NO                   VARCHAR(27)  NULL,
    SVC_ID                   VARCHAR(15)  NULL,
    VT_ACN_CRD_CONN_ST_DV_CD VARCHAR(12)  NOT NULL,
    CONN_DTTM                DATE         NULL,
    CONN_DSBL_DTTM           DATE         NULL,
    CRD_ISU_BAT_ID           VARCHAR(256) NULL,
    VAM_MACN_LIST_SNO        NUMBER(22)   NULL,
    SYS_CRE_DTTM             DATE         NULL,
    SYS_CRE_ID               VARCHAR(30)  NULL,
    SYS_UPD_DTTM             DATE         NULL,
    SYS_UPD_ID               VARCHAR(30)  NULL
);

COMMENT ON TABLE VAM.VAM_VT_ACN_LIST IS '가상 계좌 목록';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.VT_ACN_LIST_SNO IS '가상계좌목록일련번호';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.ENC_VT_ACNO IS '암호화가상계좌번호';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.BANK_CD IS '은행코드';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.VT_ACN_ST_DV_CD IS '가상계좌상태구분코드';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.VT_ACN_CONN_DV_CD IS '가상계좌연결구분코드';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.PAR_NO IS 'PAR번호';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.SVC_ID IS '서비스ID';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.VT_ACN_CRD_CONN_ST_DV_CD IS '가상계좌카드연결상태구분코드';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.CONN_DTTM IS '연결일시';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.CONN_DSBL_DTTM IS '연결해제일시';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.CRD_ISU_BAT_ID IS '카드발급배치ID';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.VAM_MACN_LIST_SNO IS '모계좌목록일련번호';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.SYS_CRE_DTTM IS '시스템생성일시';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.SYS_CRE_ID IS '시스템생성자ID';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.SYS_UPD_DTTM IS '시스템수정일시';
COMMENT ON COLUMN VAM.VAM_VT_ACN_LIST.SYS_UPD_ID IS '시스템수정자ID';

ALTER TABLE VAM.VAM_VT_ACN_LIST
ADD CONSTRAINT FK_VAM_MACN_LIST_SNO FOREIGN KEY (VAM_MACN_LIST_SNO) REFERENCES VAM.VAM_MACN_LIST (VAM_MACN_LIST_SNO);

INSERT INTO VAM.VAM_VT_ACN_LIST
SELECT VT_ACN_LIST_SNO,
       ENC_VT_ACNO,
       BANK_CD,
       VT_ACN_ST_DV_CD,
       VT_ACN_CONN_DV_CD,
       PAR_NO,
       SVC_ID,
       VT_ACN_CRD_CONN_ST_DV_CD,
       CONN_DTTM,
       CONN_DSBL_DTTM,
       CRD_ISU_BAT_ID,
       NULL,
       SYS_CRE_DTTM,
       SYS_CRE_ID,
       SYS_UPD_DTTM,
       SYS_UPD_ID
FROM VAM.VAM_VT_ACN_LIST_BACKUP;
COMMIT;

DROP TABLE VAM.VAM_VT_ACN_LIST_BACKUP;