-- `VAM_MACN_LIST` Table 생성
CREATE TABLE VAM.VAM_MACN_LIST
(
    VAM_MACN_LIST_SNO NUMBER(22)  PRIMARY KEY,
    ENC_MACN_NO       VARCHAR(44) NULL,
    BANK_CD           VARCHAR(3)  NOT NULL,
    SYS_CRE_DTTM      DATE        NULL,
    SYS_CRE_ID        VARCHAR(30) NULL,
    SYS_UPD_DTTM      DATE        NULL,
    SYS_UPD_ID        VARCHAR(30) NULL
);

COMMENT ON TABLE VAM.VAM_MACN_LIST IS '모계좌 목록';
COMMENT ON COLUMN VAM.VAM_MACN_LIST.VAM_MACN_LIST_SNO IS '모계좌목록일련번호';
COMMENT ON COLUMN VAM.VAM_MACN_LIST.ENC_MACN_NO IS '암호화모계좌번호';
COMMENT ON COLUMN VAM.VAM_MACN_LIST.BANK_CD IS '은행코드';
COMMENT ON COLUMN VAM.VAM_MACN_LIST.SYS_CRE_DTTM IS '시스템생성일시';
COMMENT ON COLUMN VAM.VAM_MACN_LIST.SYS_CRE_ID IS '시스템생성자ID';
COMMENT ON COLUMN VAM.VAM_MACN_LIST.SYS_UPD_DTTM IS '시스템수정일시';
COMMENT ON COLUMN VAM.VAM_MACN_LIST.SYS_UPD_ID IS '시스템수정자ID';
COMMIT;

-- IDX_CHRG_TR_HIST_GMNO 인덱스 생성
CREATE INDEX VAM.IDX_VAM_MACN_LIST_MACN_NO ON VAM.VAM_MACN_LIST (ENC_MACN_NO, BANK_CD);

-- VAM_MACN_LIST_SNO_SEQ 시퀀스 생성
CREATE SEQUENCE VAM.VAM_MACN_LIST_SNO_SEQ START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE NOMAXVALUE;