-- `VAM_WR_BANK_GM_LNK_HIST.ENC_DEPSP_NM` Column 변경
ALTER TABLE VAM.VAM_WR_BANK_GM_LNK_HIST MODIFY (ENC_DEPSP_NM NULL);
COMMIT;

-- `VAM_WR_BANK_GM_LNK_HIST.CSH_DEPS_YN` Column 변경
ALTER TABLE VAM.VAM_WR_BANK_GM_LNK_HIST MODIFY (CSH_DEPS_YN NULL);
COMMIT;

-- `VAM_WR_BANK_GM_LNK_HIST.WR_BANK_BRCH_TYPE_CD` Column 변경
ALTER TABLE VAM.VAM_WR_BANK_GM_LNK_HIST MODIFY (WR_BANK_BRCH_TYPE_CD NULL);
COMMIT;

-- `VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_RSP_CD` Column 변경
ALTER TABLE VAM.VAM_WR_BANK_GM_LNK_HIST MODIFY (WR_BANK_RSP_CD NULL);
COMMIT;