-- `VAM_CHRG_TR_HIST` Table 백업
ALTER TABLE VAM.VAM_CHRG_TR_HIST RENAME TO VAM_CHRG_TR_HIST_BACKUP;

-- `VAM_CHRG_TR_HIST` Table 생성
CREATE TABLE VAM.VAM_CHRG_TR_HIST
(
    CHRG_TR_HIST_SNO NUMBER(22) NOT NULL,
    CHRG_TR_HIST_GMNO VARCHAR(30) NOT NULL,
    CHRG_TR_DV_CD VARCHAR(10) NOT NULL,
    RS_ST_CD VARCHAR(10) NOT NULL,
    CRD_CHRG_AMT NUMBER NULL,
    ENC_VT_ACNO VARCHAR(44) NULL,
    BANK_CD VARCHAR(3) NOT NULL,
    PAR_NO VARCHAR(27) NOT NULL,
    SVC_ID VARCHAR(15) NOT NULL,
    TRAN_ID VARCHAR(30) NULL,
    NR_NO VARCHAR(18) NULL,
    RC_ID VARCHAR(15) NULL,
    CHRG_RQS_DTTM DATE NULL,
    CHRG_TR_CNCL_ST_DV_CD VARCHAR(6) NULL,
    CHRG_TR_CNCL_ORG_GMNO VARCHAR(30) NULL,
    CHRG_CNCL_DTTM DATE NULL,
    FAIL_RSN_CN VARCHAR(300) NULL,
    SYS_CRE_DTTM DATE NULL,
    SYS_CRE_ID VARCHAR(30) NULL,
    SYS_UPD_DTTM DATE NULL,
    SYS_UPD_ID VARCHAR(30) NULL
);

COMMENT ON TABLE VAM.VAM_CHRG_TR_HIST IS '충전 거래 이력';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.CHRG_TR_HIST_SNO IS '충전거래이력일련번호';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.CHRG_TR_HIST_GMNO IS '충전거래이력전문번호';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.CHRG_TR_DV_CD IS '충전거래구분코드';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.RS_ST_CD IS '결과상태코드';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.CRD_CHRG_AMT IS '카드충전금액';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.ENC_VT_ACNO IS '암호화가상계좌번호';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.BANK_CD IS '은행코드';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.PAR_NO IS 'PAR번호';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.SVC_ID IS '서비스ID';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.TRAN_ID IS '트랜잭션ID';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.NR_NO IS 'NR번호';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.RC_ID IS '충전상ID';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.CHRG_RQS_DTTM IS '충전요청일시';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.CHRG_TR_CNCL_ST_DV_CD IS '충전거래취소상태구분코드';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.CHRG_TR_CNCL_ORG_GMNO IS '충전거래취소원전문번호';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.CHRG_CNCL_DTTM IS '충전취소일시';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.FAIL_RSN_CN IS '실패사유내용';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.SYS_CRE_DTTM IS '시스템생성일시';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.SYS_CRE_ID IS '시스템생성자ID';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.SYS_UPD_DTTM IS '시스템수정일시';
COMMENT ON COLUMN VAM.VAM_CHRG_TR_HIST.SYS_UPD_ID IS '시스템수정자ID';

-- IDX_CHRG_TR_HIST_GMNO 인덱스 생성
CREATE INDEX VAM.IDX_CHRG_TR_HIST_GMNO ON VAM.VAM_CHRG_TR_HIST (CHRG_TR_HIST_SNO);
CREATE INDEX VAM.IDX_CHRG_TR_CNCL_ORG_GMNO ON VAM.VAM_CHRG_TR_HIST (CHRG_TR_CNCL_ORG_GMNO);

--- `VAM.VAM_CHRG_TR_HIST` 백업 데이터 추가
INSERT INTO VAM.VAM_CHRG_TR_HIST
SELECT CHRG_TR_HIST_SNO,
       CHRG_TR_HIST_GMNO,
       CHRG_TR_DV_CD,
       RS_ST_CD,
       CRD_CHRG_AMT,
       ENC_VT_ACNO,
       BANK_CD,
       PAR_NO,
       SVC_ID,
       TRAN_ID,
       NR_NO,
       RC_ID,
       CHRG_RQS_DTTM,
       CHRG_TR_CNCL_ST_DV_CD,
       NULL,
       CHRG_CNCL_DTTM,
       FAIL_RSN_CN,
       SYS_CRE_DTTM,
       SYS_CRE_ID,
       SYS_UPD_DTTM,
       SYS_UPD_ID
FROM VAM.VAM_CHRG_TR_HIST_BACKUP;
COMMIT;

-- `VAM.VAM_CHRG_TR_HIST_BACKUP` 테이블 삭제
DROP TABLE VAM.VAM_CHRG_TR_HIST_BACKUP;