server:
  port: 11020
  servlet:
    context-path: /vam

spring:
  datasource:
    url: jdbc:oracle:thin:@118.33.122.30:15321:KMDBP
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: map
    password: StgMAP1104#
