# server
server:
  shutdown: graceful
  servlet:
    context-path: /vam
  tomcat:
    threads:
      min-spare: 10
      max: 200
    connection-timeout: 20s

# springdoc
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    doc-expansion: none

# actuator
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, shutdown, metrics, prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false

# masking
masking:
  fields: token|6|4

# encrypt cubeone
database:
  encrypt-provider: CUBE_ONE

# spring
spring:
  datasource:
    hikari:
      pool-name: hikaricp-pool
      driver-class-name: oracle.jdbc.driver.OracleDriver
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 60000
      idle-timeout: 30000
      connection-timeout: 10000
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    database: oracle
  data:
    redis:
      timeout: 10s
      connect-timeout: 10s
      lettuce:
        pool:
          enabled: true
          min-idle: 0
          max-idle: 8
          max-active: 30
          max-wait: 20s
          time-between-eviction-runs: 20s

# logging
logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.40.10.24:15322:KMDBP19
    username: vam
    password: xBA0tTwL9zl+MqCkvfkGQw==
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: 10.30.210.121
      port: 6379
      password: 123456
      sentinel:
        master: mymaster
        nodes: 10.30.210.121:26379

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.30.200.114:15321:KMDBP
    username: vam
    password: xBA0tTwL9zl+MqCkvfkGQw==
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: 10.30.210.153
      port: 6379
      password: 123456
      sentinel:
        master: mymaster
        nodes: 10.30.210.153:26379

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@db.konadc.com:15321/kmdbp
    username: vam
    password: IrYdRa16loALOEikHzrRXA==
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  data:
    redis:
      password: 123456
      sentinel:
        master: mymaster
        nodes: redis1.konadc.com:26379, redis2.konadc.com:26379, redis3.konadc.com:26379