server:
  port: 11020
  shutdown: graceful
  servlet:
    context-path: /vam
#  undertow:
#    threads:
#      io: 32
#      worker: 256
#    no-request-timeout: 300000

# actuator
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,shutdown,metrics,prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false

# masking
masking:
  fields: FIELD|token|6|4, FIELD|aspId|4|4, FIELD|di|0|0, FIELD|ci|0|0, FIELD|mapId|0|0, FIELD|address|2|0, FIELD|mobileTokenList|2|0, FIELD|cardInfoList|2|0

# encrypt cubeone
database:
  encrypt-provider: CUBE_ONE

# spring
spring:
  datasource:
    hikari:
      pool-name: hikaricp-pool
      driver-class-name: oracle.jdbc.driver.OracleDriver
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 60000
      idle-timeout: 30000
      connection-timeout: 10000
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    database: oracle

# logging
logging:
  level:
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.apache.hc.client5.http: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.40.10.24:15322:KMDBP19
    username: fxs
    password: CXWLYpdVO7die8haH1l9+A==
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        show_sql: true
  data:
    redis:
      host: 10.30.210.121
      password: 123456
      port: 6379
      timeout: 500
      sentinel:
        master: mymaster
        nodes: ['10.30.210.121:26379']

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.30.200.114:15321:KMDBP
    username: fxs
    password: StgFXS1104#
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: false
  data:
    redis:
      host: redis.kpp.com
      password: 123456
      port: 6379
      timeout: 500
      sentinel:
        master: mymaster
        nodes: ['redis.kpp.com:26379']

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@db.konadc.com:15321:kmdbp
    username: fxs
    password: CXWLYpdVO7die8haH1l9+A==
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: false
  data:
    redis:
      host: redis.kpp.com
      password: 123456
      port: 6379
      timeout: 500
      sentinel:
        master: mymaster
        nodes: ['redis.kpp.com:26379']
