-- `VAM_WR_BANK_TR_AGG` Table 생성


CREATE TABLE VAM.VAM_WR_BANK_TR_AGG
(
    AGG_DT VARCHAR(8) NOT NULL,
    AGG_RS_DV_CD VARCHAR(10) NOT NULL,
    KN_DEPS_CCNT NUMBER NOT NULL,
    KN_DEPS_AMT NUMBER NOT NULL,
    KN_DEPS_CNCL_CCNT NUMBER NOT NULL,
    KN_DEPS_CNCL_AMT NUMBER NOT NULL,
    KN_PURE_DEPS_AMT NUMBER NOT NULL,
    WR_BANK_DEPS_CCNT NUMBER NULL,
    WR_BANK_DEPS_AMT NUMBER NULL,
    WR_BANK_DEPS_CNCL_CCNT NUMBER NULL,
    WR_BANK_DEPS_CNCL_AMT NUMBER NULL,
    WR_BANK_PURE_DEPS_AMT NUMBER NULL,
    SYS_CRE_DTTM DATE NULL,
    SYS_CRE_ID VARCHAR(30) NULL,
    SYS_UPD_DTTM DATE NULL,
    SYS_UPD_ID VARCHAR(30) NULL
);


COMMENT ON TABLE VAM.VAM_WR_BANK_TR_AGG IS '우리은행 거래 집계';

COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.AGG_DT IS '집계일자';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.AGG_RS_DV_CD IS '집계결과구분코드';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.KN_DEPS_CCNT IS '코나입금건수';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.KN_DEPS_AMT IS '코나입금금액';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.KN_DEPS_CNCL_CCNT IS '코나입금취소건수';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.KN_DEPS_CNCL_AMT IS '코나입금취소금액';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.KN_PURE_DEPS_AMT IS '코나순입금금액';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.WR_BANK_DEPS_CCNT IS '우리은행입금건수';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.WR_BANK_DEPS_AMT IS '우리은행입금금액';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.WR_BANK_DEPS_CNCL_CCNT IS '우리은행입금취소건수';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.WR_BANK_DEPS_CNCL_AMT IS '우리은행입금취소금액';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.WR_BANK_PURE_DEPS_AMT IS '우리은행순입금금액';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.SYS_CRE_DTTM IS '시스템생성일시';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.SYS_CRE_ID IS '시스템생성자ID';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.SYS_UPD_DTTM IS '시스템수정일시';
COMMENT ON COLUMN VAM.VAM_WR_BANK_TR_AGG.SYS_UPD_ID IS '시스템수정자ID';





CREATE UNIQUE INDEX VAM.PK_VAM_WR_BANK_TR_AGG ON VAM.VAM_WR_BANK_TR_AGG
    (AGG_DT);

ALTER TABLE VAM.VAM_WR_BANK_TR_AGG ADD (
 CONSTRAINT PK_VAM_WR_BANK_TR_AGG
 PRIMARY KEY (AGG_DT)
USING INDEX PK_VAM_WR_BANK_TR_AGG);

