-- `VAM_VT_ACN_BANK_LIST` Table 생성
CREATE TABLE VAM.VAM_VT_ACN_BANK_LIST
(
    VT_ACN_BANK_CD VARCHAR(3) NOT NULL,
    BANK_ENM VARCHAR(300) NOT NULL,
    BANK_NM VARCHAR(100) NOT NULL,
    RC_ID VARCHAR(15) NULL,
    SYS_CRE_DTTM DATE NULL,
    SYS_CRE_ID VARCHAR(30) NULL,
    SYS_UPD_DTTM DATE NULL,
    SYS_UPD_ID VARCHAR(30) NULL
);


COMMENT ON TABLE VAM.VAM_VT_ACN_BANK_LIST IS '가상 계좌 은행 목록';

COMMENT ON COLUMN VAM.VAM_VT_ACN_BANK_LIST.VT_ACN_BANK_CD IS '가상계좌은행코드';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BANK_LIST.BANK_ENM IS '은행영문명';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BANK_LIST.BANK_NM IS '은행명';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BANK_LIST.RC_ID IS '충전상ID';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BANK_LIST.SYS_CRE_DTTM IS '시스템생성일시';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BANK_LIST.SYS_CRE_ID IS '시스템생성자ID';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BANK_LIST.SYS_UPD_DTTM IS '시스템수정일시';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BANK_LIST.SYS_UPD_ID IS '시스템수정자ID';





CREATE UNIQUE INDEX VAM.PK_VAM_VT_ACN_BANK_LIST ON VAM.VAM_VT_ACN_BANK_LIST
    (VT_ACN_BANK_CD);

ALTER TABLE VAM.VAM_VT_ACN_BANK_LIST ADD (
 CONSTRAINT PK_VAM_VT_ACN_BANK_LIST
 PRIMARY KEY (VT_ACN_BANK_CD)
USING INDEX PK_VAM_VT_ACN_BANK_LIST);
