-- `VAM_VT_ACN_BAT_HIST` Table 생성
CREATE TABLE VAM.VAM_VT_ACN_BAT_HIST
(
    VT_ACN_BAT_HIST_SNO NUMBER(22) NOT NULL,
    CRD_ISU_BAT_ID VARCHAR(256) NOT NULL,
    SVC_ID VARCHAR(15) NOT NULL,
    VT_ACN_BAT_QTY NUMBER NOT NULL,
    RS_ST_CD VARCHAR(10) NULL,
    FAIL_RSN_CN VARCHAR(300) NULL,
    FILE_PTH_NM VARCHAR(300) NULL,
    SYS_CRE_DTTM DATE NULL,
    SYS_CRE_ID VARCHAR(30) NULL,
    SYS_UPD_DTTM DATE NULL,
    SYS_UPD_ID VARCHAR(30) NULL
);


COMMENT ON TABLE VAM.VAM_VT_ACN_BAT_HIST IS '가상 계좌 배치 이력';

COMMENT ON COLUMN VAM.VAM_VT_ACN_BAT_HIST.VT_ACN_BAT_HIST_SNO IS '가상계좌배치이력일련번호';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BAT_HIST.CRD_ISU_BAT_ID IS '카드발급배치ID';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BAT_HIST.SVC_ID IS '서비스ID';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BAT_HIST.VT_ACN_BAT_QTY IS '가상계좌배치수량';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BAT_HIST.RS_ST_CD IS '결과상태코드';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BAT_HIST.FAIL_RSN_CN IS '실패사유내용';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BAT_HIST.FILE_PTH_NM IS '파일경로명';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BAT_HIST.SYS_CRE_DTTM IS '시스템생성일시';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BAT_HIST.SYS_CRE_ID IS '시스템생성자ID';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BAT_HIST.SYS_UPD_DTTM IS '시스템수정일시';
COMMENT ON COLUMN VAM.VAM_VT_ACN_BAT_HIST.SYS_UPD_ID IS '시스템수정자ID';





CREATE UNIQUE INDEX VAM.PK_VAM_VT_ACN_BAT_HIST ON VAM.VAM_VT_ACN_BAT_HIST
    (VT_ACN_BAT_HIST_SNO);

ALTER TABLE VAM.VAM_VT_ACN_BAT_HIST ADD (
 CONSTRAINT PK_VAM_VT_ACN_BAT_HIST
 PRIMARY KEY (VT_ACN_BAT_HIST_SNO)
USING INDEX PK_VAM_VT_ACN_BAT_HIST);


-- `VT_ACN_BAT_HIST_SNO_SEQ` Sequence 생성
CREATE SEQUENCE VAM.VT_ACN_BAT_HIST_SNO_SEQ START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE NOMAXVALUE;