-- `VAM_WR_BANK_GM_LNK_HIST` Table 생성
CREATE TABLE VAM.VAM_WR_BANK_GM_LNK_HIST
(
    WR_BANK_GM_LNK_HIST_SNO NUMBER(22) NOT NULL,
    WR_BANK_DCRM_TYPE_CD VARCHAR(9) NOT NULL,
    WR_BANK_ENP_TYPE_CD VARCHAR(8) NOT NULL,
    WR_BANK_OGN_TYPE_CD VARCHAR(2) NOT NULL,
    WR_BANK_GM_TYPE_CD VARCHAR(4) NOT NULL,
    WR_BANK_BS_TYPE_CD VARCHAR(3) NOT NULL,
    TRSF_TMCNT NUMBER NOT NULL,
    WR_BANK_GMNO VARCHAR(6) NOT NULL,
    TRSF_DT VARCHAR(8) NOT NULL,
    TRSF_TM VARCHAR(6) NOT NULL,
    WR_BANK_RSP_CD VARCHAR(4) NOT NULL,
    WR_BANK_ORG_GMNO VARCHAR(6) NULL,
    ENC_MACN_NO VARCHAR(44) NULL,
    TR_DT VARCHAR(8) NOT NULL,
    TR_TI VARCHAR(6) NOT NULL,
    TID VARCHAR(27) NOT NULL,
    WR_BANK_TR_MDI_TYPE_CD VARCHAR(2) NOT NULL,
    WR_BANK_TR_AMT NUMBER NOT NULL,
    OBR_CSCK_AMT NUMBER NOT NULL,
    ETC_OBR_CSCK_AMT NUMBER NOT NULL,
    WR_BANK_TR_BRCH_TYPE_CD VARCHAR(6) NOT NULL,
    ENC_DEPSP_NM VARCHAR(100) NOT NULL,
    ENC_VT_ACNO VARCHAR(44) NOT NULL,
    VT_ACN_NM VARCHAR(100) NOT NULL,
    VT_ACN_BALA NUMBER NOT NULL,
    CSH_DEPS_YN VARCHAR(1) NOT NULL,
    WR_BANK_CSCK_AMT NUMBER NOT NULL,
    WR_BANK_BRCH_TYPE_CD VARCHAR(7) NOT NULL,
    DEPS_CFM_NOTI_YN VARCHAR(1) NULL,
    RSP_MSG_CN VARCHAR(2000) NULL,
    SYS_CRE_DTTM DATE NULL,
    SYS_CRE_ID VARCHAR(30) NULL,
    SYS_UPD_DTTM DATE NULL,
    SYS_UPD_ID VARCHAR(30) NULL
);


COMMENT ON TABLE VAM.VAM_WR_BANK_GM_LNK_HIST IS '우리은행 전문 연동 이력';

COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_GM_LNK_HIST_SNO IS '우리은행전문연동이력일련번호';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_DCRM_TYPE_CD IS '우리은행식별유형코드';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_ENP_TYPE_CD IS '우리은행업체유형코드';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_OGN_TYPE_CD IS '우리은행기관유형코드';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_GM_TYPE_CD IS '우리은행전문유형코드';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_BS_TYPE_CD IS '우리은행업무유형코드';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.TRSF_TMCNT IS '전송횟수';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_GMNO IS '우리은행전문번호';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.TRSF_DT IS '전송일자';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.TRSF_TM IS '전송시간';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_RSP_CD IS '우리은행응답코드';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_ORG_GMNO IS '우리은행원전문번호';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.ENC_MACN_NO IS '암호화모계좌번호';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.TR_DT IS '거래일자';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.TR_TI IS '거래시각';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.TID IS 'TID';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_TR_MDI_TYPE_CD IS '우리은행거래매체유형코드';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_TR_AMT IS '우리은행거래금액';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.OBR_CSCK_AMT IS '타점자기앞수표금액';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.ETC_OBR_CSCK_AMT IS '기타타점자기앞수표금액';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_TR_BRCH_TYPE_CD IS '우리은행거래지점유형코드';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.ENC_DEPSP_NM IS '암호화입금자명';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.ENC_VT_ACNO IS '암호화가상계좌번호';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.VT_ACN_NM IS '가상계좌명';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.VT_ACN_BALA IS '가상계좌잔액';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.CSH_DEPS_YN IS '현금입금여부';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_CSCK_AMT IS '우리은행자기앞수표금액';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.WR_BANK_BRCH_TYPE_CD IS '우리은행지점유형코드';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.DEPS_CFM_NOTI_YN IS '입금확정통보여부';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.RSP_MSG_CN IS '응답메시지내용';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.SYS_CRE_DTTM IS '시스템생성일시';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.SYS_CRE_ID IS '시스템생성자ID';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.SYS_UPD_DTTM IS '시스템수정일시';
COMMENT ON COLUMN VAM.VAM_WR_BANK_GM_LNK_HIST.SYS_UPD_ID IS '시스템수정자ID';





CREATE UNIQUE INDEX VAM.PK_VAM_WR_BANK_GM_LNK_HIST ON VAM.VAM_WR_BANK_GM_LNK_HIST
    (WR_BANK_GM_LNK_HIST_SNO);

ALTER TABLE VAM.VAM_WR_BANK_GM_LNK_HIST ADD (
 CONSTRAINT PK_VAM_WR_BANK_GM_LNK_HIST
 PRIMARY KEY (WR_BANK_GM_LNK_HIST_SNO)
USING INDEX PK_VAM_WR_BANK_GM_LNK_HIST);


-- `WR_BANK_GM_LNK_HIST_SNO_SEQ` Sequence 생성
CREATE SEQUENCE VAM.WR_BANK_GM_LNK_HIST_SNO_SEQ START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE NOMAXVALUE;