-- `VAM_CHRG_TR_HIST` Table 생성
CREATE TABLE VAM.VAM_SNO_CRE_LIST
(
    VAM_SNO_CRE_LIST_SNO NUMBER(22) PRIMARY KEY,
    VAM_SNO_CRE_DV_CD VARCHAR(20) NOT NULL,
    SNO_CRE_DT VARCHAR(8) NOT NULL,
    SNO_CRE_CRNT_VAL NUMBER(22) NOT NULL,
    SYS_CRE_DTTM DATE NULL,
    SYS_CRE_ID VARCHAR(30) NULL,
    SYS_UPD_DTTM DATE NULL,
    SYS_UPD_ID VARCHAR(30) NULL
);

COMMENT ON TABLE VAM.VAM_SNO_CRE_LIST IS 'VAM 일련번호 생성 목록';
COMMENT ON COLUMN VAM.VAM_SNO_CRE_LIST.VAM_SNO_CRE_LIST_SNO IS 'VAM 일련번호 생성 목록 SNO';
COMMENT ON COLUMN VAM.VAM_SNO_CRE_LIST.VAM_SNO_CRE_DV_CD IS 'VAM 일련번호 생성 구분 코드';
COMMENT ON COLUMN VAM.VAM_SNO_CRE_LIST.SNO_CRE_DT IS '일련번호 생성 일자';
COMMENT ON COLUMN VAM.VAM_SNO_CRE_LIST.SNO_CRE_CRNT_VAL IS '일련번호 생성 현재값';
COMMENT ON COLUMN VAM.VAM_SNO_CRE_LIST.SYS_CRE_DTTM IS '시스템생성일시';
COMMENT ON COLUMN VAM.VAM_SNO_CRE_LIST.SYS_CRE_ID IS '시스템생성자ID';
COMMENT ON COLUMN VAM.VAM_SNO_CRE_LIST.SYS_UPD_DTTM IS '시스템수정일시';
COMMENT ON COLUMN VAM.VAM_SNO_CRE_LIST.SYS_UPD_ID IS '시스템수정자ID';

-- `SNO_CRE_LIST_SNO_SEQ` Sequence 생성
CREATE SEQUENCE VAM.SNO_CRE_LIST_SNO_SEQ START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE NOMAXVALUE;

-- `UQ_IDX_VAM_VT_ACN_LIST` unique index 생성
CREATE UNIQUE INDEX VAM.UQ_IDX_VAM_VT_ACN_LIST ON VAM.VAM_SNO_CRE_LIST(VAM_SNO_CRE_DV_CD, SNO_CRE_DT);
