-- `VAM_CHRG_TR_HIST` Table 생성
CREATE TABLE VAM.VAM_SNO_CRE_LIST
(
    SNO_CRE_LIST_SNO NUMBER(22) PRIMARY KEY,
    SNO_CRE_DT VARCHAR(8) NOT NULL,
    SNO_CRE_DV_CD VARCHAR(20) NOT NULL,
    SNO_CRE_CRNT_VAL NUMBER(22) NOT NULL,
    SYS_CRE_DTTM DATE NULL,
    SYS_CRE_ID VARCHAR(30) NULL,
    SYS_UPD_DTTM DATE NULL,
    SYS_UPD_ID VARCHAR(30) NULL
);

-- `SNO_CRE_LIST_SNO_SEQ` Sequence 생성
CREATE SEQUENCE VAM.SNO_CRE_LIST_SNO_SEQ START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE NOMAXVALUE;

-- `UQ_IDX_VAM_VT_ACN_LIST` unique index 생성
CREATE UNIQUE INDEX VAM.UQ_IDX_VAM_VT_ACN_LIST ON VAM.VAM_SNO_CRE_LIST(SNO_CRE_DT, SNO_CRE_DV_CD);
